---
language:           node_js

notifications:
  email:            false

node_js:
  - 9
  - 8
  - 7
  - 6
  - node

before_script:
  - npm prune

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | coveralls
